yarntail_project/yarntail/urls.py
from django.conf.urls import patterns, url
from yarntail import views
import yarntail

urlpatterns = patterns('',

                       url(r'^$', views.index_popular, name='index'),

                       #search
                       url(r'^search/$', yarntail.views.search_autocomplete, name='search_autocomplete'),
                       url(r'^search_results/$', yarntail.views.search_results, name='search_results'),
                       # url(r'^search_results/(?P<query>[\w\-+]+)$', yarntail.views.search_results,
                       #     name='search_results'),#search works without this, as there is now no need for <query>


                       url(r'^index/$', views.index_popular, name='index'),
                       url(r'^index/latest/$', views.index_latest, name='index_latest'),
                       url(r'^index/popular/$', views.index_popular, name='index_popular'),
                       url(r'^index/all/$', views.index_all, name='index_all'),

                       url(r'^about_us/$', views.about, name='about'),
                       url(r'^search/(?P<query_slug>[\w\-]+)/$', views.search_autocomplete, name='search'),

                       # Profile Related
                       url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
                       url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
                       url(r'add_profile/$', views.register_profile, name='add_profile'),

                       #Pattern Related
                       url(r'^pattern/(?P<username_slug>[\w\-]+)/(?P<pattern_slug>[\w\-]+)/$', views.pattern,
                           name='pattern'),
                       url(r'^what_is_YarnTail/$', views.what_is_yarntail, name='what_is_yarntail'),
                       url(r'^upload_instructions/$', views.upload_instructions, name='upload_instructions'),
                       url(r'^add_pattern/$', views.add_pattern, name='add_pattern'),
                       url(r'^edit_pattern/(?P<username_slug>[\w\-]+)/(?P<pattern_slug>[\w\-]+)/$', views.edit_pattern, name='edit_pattern'),



                       )


# Josh - added yarntail. in front of views because it fixed an issue with the search

yarntail_project/yarntail_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from registration.backends.simple.views import RegistrationView

from yarntail import views
import settings


class MyRegistrationView(RegistrationView):
    def get_success_url(selfself,request, user):
        return '/yarntail/add_profile/'

urlpatterns = patterns('',
                       url(r'^$', views.index_popular, name='index_popular'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^yarntail/', include('yarntail.urls')),
                       url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^accounts/', include('registration.backends.simple.urls')),
                       url(r'^search/', include('haystack.urls')),
                       )

handler400 = 'yarntail.views.handle404'
handler404 = 'yarntail.views.handle404'
handler500 = 'yarntail.views.handle404'

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',(r'^media/(?P<path>.*)','serve',{'document_root': settings.MEDIA_ROOT}), )

yarntail_project/yarntail/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
import ast


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile')
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    date_of_birth = models.DateField()
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)


    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('profile', kwargs={'username': self.user.username})


class Pattern(models.Model):
    title = models.CharField(max_length=128,
                             unique=True)
    user = models.ForeignKey(User, related_name='patterns')
    likes = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    description = models.CharField(max_length=3000)
    creation_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    design = models.CharField(max_length=100000, default="empty pattern")
    HARD = 'Hard'
    MEDIUM = 'Medium'
    EASY = 'Easy'
    DIFFICULTY_CHOICES = (
        (HARD, 'Hard'),
        (MEDIUM, 'Medium'),
        (EASY, 'Easy'),
    )
    difficulty = models.CharField(default="Easy", choices=DIFFICULTY_CHOICES, max_length=10)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Pattern, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('pattern', kwargs={'username_slug': self.user.user_profile.slug, 'pattern_slug': self.slug})


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='comments')
    pattern = models.ForeignKey(Pattern, related_name='pattern')
    creation_date = models.DateTimeField(auto_now_add=True)
    comment_string = models.CharField(max_length=20000)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.creation_date)
        super(Comment, self).save(*args, **kwargs)

    def __unicode__(self):
        return unicode(self.creation_date)

yarntail_project/yarntail/forms.py
import user
from django import forms
from django.db import models
from django.forms import ModelForm
from models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'picture', 'date_of_birth')

class PatternForm(forms.ModelForm):
    slug = forms.CharField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Pattern
        fields = ('title', 'description', 'difficulty', 'design') #removed slug

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_string',)

yarntail_project/yarntail/views.py
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from forms import UserProfileForm, PatternForm, CommentForm
from models import *
from haystack.query import SearchQuerySet



def index_popular(request):
    context_dict = {}

    popular_patterns = Pattern.objects.filter().order_by('-views')[:20]
    context_dict['popular_patterns'] = popular_patterns

    return render(request, 'yarntail/index_popular.html', context_dict)


def index_latest(request):
    context_dict = {}

    latest_patterns = Pattern.objects.filter().order_by('-creation_date')[:20]
    context_dict['latest_patterns'] = latest_patterns

    return render(request, 'yarntail/index_latest.html', context_dict)


def index_all(request):
    context_dict = {}

    all_patterns = Pattern.objects.filter().order_by('-creation_date')
    context_dict['patterns_all'] = all_patterns

    return render(request, 'yarntail/index_all.html', context_dict)


def about(request):
    return render(request, 'yarntail/about.html')


@login_required
def profile(request, username):
    u = User.objects.get(username=username)
    context_dict = {}

    try:
        user_profile = UserProfile.objects.get(user=u)
    except:
        user_profile = None

    patterns = Pattern.objects.filter(user=u).order_by('-views')

    context_dict['u'] = u
    context_dict['userprofile'] = user_profile
    context_dict['patterns'] = patterns

    return render(request, 'yarntail/profile.html', context_dict)


def register_profile(request):
    if request.method == 'POST':
        try:
            userProfile = UserProfile.objects.get(user=request.user)
            form = UserProfileForm(request.POST, request.FILES, instance=request.user)
        except:
            form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            if request.user.is_authenticated():
                profile = form.save(commit=False)
                user = User.objects.get(id=request.user.id)
                profile.user = user
                try:
                    profile.picture = request.FILES['picture']
                except:
                    pass
                profile.save()
        else:
            print form.errors
        return render(request, 'registration/registration_complete.html')
    else:
        form = UserProfileForm(request.GET)

    return render(request, 'yarntail/profile_registration.html', {'profile_form': form})


@login_required
def edit_profile(request):
    if request.method == "POST":

        try:
            profile = UserProfile.objects.get(user=request.user)
            profileForm = UserProfileForm(request.POST, instance=profile)
        except:
            profileForm = UserProfileForm(request.POST)

        if profileForm.is_valid():

            if request.user.is_authenticated():
                profile = profileForm.save(commit=False)
                user = request.user
                profile.user = user

                try:
                    profile.picture = request.FILES['picture']
                except:
                    pass
                profile.save()
        else:
            print profileForm.errors

        return redirect('profile', profile.user)
    else:
        profileForm = UserProfileForm(request.GET)

    context_dict = {}
    context_dict['profile'] = profileForm

    return render(request, 'yarntail/edit_profile.html', context_dict)

def pattern(request, username_slug, pattern_slug):
    username = username_slug.lower()
    context_dict = {}
    profile = UserProfile.objects.get(slug=username)
    user = User.objects.get(user_profile=profile)
    pattern = Pattern.objects.get(user=user, slug=pattern_slug)
    comment = Comment.objects.filter(pattern=pattern).order_by('-creation_date')

    pattern.views += 1
    pattern.save()

    context_dict['u'] = user

    context_dict['pattern'] = pattern
    context_dict['views'] = pattern.views

    context_dict['comment'] = comment

    if request.user.is_authenticated():
        form = CommentForm(request.GET)
        if request.method == 'POST':
            form = CommentForm(request.POST)

            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.pattern = Pattern.objects.get(slug=pattern_slug)
                comment.save()
            else:
                print form.errors

    return render(request, 'yarntail/pattern.html', context_dict)


def edit_pattern(request, username_slug, pattern_slug):
    c = {}
    context_dict = {}
    if request.user.is_authenticated():
        pattern = Pattern.objects.get(slug=pattern_slug)
        form = PatternForm(request.POST, instance=pattern)
        if request.method == 'POST':
            context_dict['csrf_token'] = c.update(csrf(request))
            form = PatternForm(request.POST, instance=pattern)
            print "user authenticated"
            if form.is_valid():
                print "form valid"
                patternform = form.save(commit=False)
                patternform.user = User.objects.get(id=request.user.id)
                patternform.save()
            else:
                print form.errors
            return redirect('pattern', pattern.user, pattern.slug)
        context_dict['pattern_form'] = form
        context_dict['pattern'] = pattern
        context_dict['u'] = request.user
        return render(request, 'yarntail/edit_pattern.html', context_dict)
    else:
        return redirect(index_popular(request))


@login_required
def add_pattern(request):
    c = {}
    context_dict = {}
    pattern = None
    if request.user.is_authenticated():
        form = PatternForm(request.GET)
        if request.method == 'POST':
            context_dict['csrf_token'] = c.update(csrf(request))
            form = PatternForm(request.POST)

            if form.is_valid():
                pattern = form.save(commit=False)
                pattern.user = User.objects.get(id=request.user.id)
                pattern.save()

            else:
                print form.errors
            try:
                return redirect('pattern', pattern.user, pattern.slug)
            except:
                return handle404(request)
        context_dict['pattern_form'] = form
        return render(request, 'yarntail/add_pattern.html', context_dict)
    else:
        return redirect(index_popular(request))


def what_is_yarntail(request):
    return render(request, 'yarntail/what_is_yarntail.html')


def upload_instructions(request):
    return render(request, 'yarntail/upload_instructions.html')


def get_patterns(max_results=0, contains=''):
    pattern_list = []
    if contains:
        pattern_list = Pattern.objects.filter(title__contains=contains)

    if max_results > 0:
        if len(pattern_list) > max_results:
            pattern_list = pattern_list[:max_results]
    return pattern_list

@csrf_exempt
def search_autocomplete(request):#make compatible with users

    final_results = {}
    patterns = []
    users = []
    p=None
    u=None
    query = request.POST['search_text']



    if query:

        query_results = SearchQuerySet().autocomplete(content_auto=query)
        for result in query_results:
            try:
                p = Pattern.objects.get(pk=result.pk)
                if query.lower() not in p.lower():
                    p = None
            except:
                pass

            try:
                u = UserProfile.objects.get(pk=result.pk)
                if query.lower() not in u.user.username.lower():
                    u = None
            except:
                pass

            if u != None:
                users.append({'name': u.user.username, 'url': u.get_absolute_url()})
            if p != None:
                patterns.append({'title': p.title, 'url': p.get_absolute_url()})
            u = p = None

        final_results['patterns'] = patterns
        final_results['users'] = users

    return JsonResponse(final_results, safe=False)


def search_results(request):
    context_dict = {}
    patterns = []
    users = []
    p=None
    u=None
    query = request.GET.urlencode().replace("search=", "")
    if query:
        query_results = SearchQuerySet().filter(text=query)



        for result in query_results:
            try:
                p = Pattern.objects.get(pk=result.pk)
                if query.lower() not in p.lower():
                    p = None
            except:
                pass

            try:
                u = UserProfile.objects.get(pk=result.pk)
                if query.lower() not in u.user.username.lower():
                    u = None
            except:
                pass

            if u != None:
                users.append(u)
            if p != None:
                patterns.append(p)
            u = p = None

            context_dict['users'] = users
            context_dict['patterns'] = patterns
            context_dict['num_users'] = len(users)
            context_dict['num_patterns'] = len(patterns)
            context_dict['num_all'] = len(patterns) + len(users)

    return render(request, "yarntail/search_results.html", context_dict)


def handle404(request):
    return render(request, "yarntail/page_not_found.html")

yarntail_project/templates/yarntail/about.html
{% extends 'yarntail/base.html' %}

{% load staticfiles %}
{% block body_block %}

<div class="page-header">
    <h1>About Us</h1>
</div>

<h2>YarnTail was brought to you by:<br/></h2>


<p> <strong>Rui Da Silva Costa</strong>, 2087521 <br/>
    <strong>Jake Degiovanni</strong>, 2066890 <br/>
    <strong>Josh Marsh</strong>, 2155744 <br/>
    <strong>Jack Parkinson</strong>, 2082657 <br/>
    <strong>Cordelia Schmid</strong>, 2038363 <br/>
    <br/>

</p>

<div style="height:500px; width:500px">
                <img src="/static/images/about.jpg" alt="About Us"
                     style="max-width:100%;max-height:100%;margin:auto;display:block"/>
            </div>


{% endblock %}

yarntail_project/templates/yarntail/add_pattern.html
{% extends "yarntail/base.html" %}

{% load staticfiles %}

{% block body_block %}
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
		<script src="/static/js/script.js"></script>
		<link rel="stylesheet" type="text/css" href="/static/css/stylesheet.css">
    </head>


    <body onload="adjust_axis()">

    <div role="tabpanel">

        <!-- NAV TABS -->
        <ul class="nav nav-tabs nav-justified" role="tablist">
            <li role="presentation" class="active"><a href="#graphical_input" aria-controls="graphical_input" role="tab"
                                                      data-toggle="tab">Design Input</a></li>
            <li role="presentation"><a href="#save_and_submit" aria-controls="save_and_submit" role="tab"
                                       onclick="map_maker()"
                                       data-toggle="tab">Save and Submit</a></li>
        </ul>

        <!-- TAB CONTENT -->
        <div class="tab-content">
            <!-- GRAPIHCAL INPUT TAB -->
            <div role="tabpanel" class="tab-pane active" id="graphical_input" style="nopadding">
                <div class="row">
                    <div class="col-md-6 nopadding">
                        <h3>Select a size for your canvas</h3>

                        <div class="row">
                            <form name="sizeInput">
                                <div class="col-md-6">
                                    <h4>X-axis size:</h4>
                                    <input type="number" class="form-control" value="20" id="xInput">
                                    <div class="row">
                                        </br>

                                        <div class="col-md-8">
                                            <button type="button" class="btn btn-primary btn-lg btn-block"
                                                    onclick="adjust_axis()">Adjust Axis
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <h4>Y-axis size:</h4>
                                    <input type="number" class="form-control" value="20" id="yInput">


                                </div>
                            </form>


                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <h3>Instructions</h3>

                                <div class="well well-lg">
                                    <p><i><strong>Click</strong> a square to cycle between knit, purl, and no stitch <br/>
                                        <strong>Drag</strong> colors from the palette below into squares you want to color<br/>
                                        <strong>Resize</strong> the grid by adjusting the x and y values above.</i></p>
                                    <img id="knit_legend" src="/static/images/knit_legend.png">
                                    <label for="knit_legend">Knit Stitch   </label>
                                    <img id="purl_legend" src="/static/images/purl.png">
                                    <label for="purl_legend">Purl Stitch</label><br>
                                    <img id="drop_legend" src="/static/images/drop.png">
                                    <label for="drop_legend">Drop Stitch</label><br>
                                </div>
                                <h3>Drag a colour onto a stitch to colour it</h3>
                                <table>
                                    <tr>
                                        <td id="#FFFFFF" bgcolor="FFFFFF" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#000000" bgcolor="000000" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#C91111" bgcolor="C91111" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#D84E09" bgcolor="D84E09" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#FF8000" bgcolor="FF8000" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#F6EB20" bgcolor="F6EB20" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#51C201" bgcolor="51C201" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#1C8E0D" bgcolor="1C8E0D" draggable="true"
                                            ondragstart="drag(event)"></td>
                                    </tr>
                                    <tr>
                                        <td id="#09C5F4" bgcolor="09C5F4" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#2862B9" bgcolor="2862B9" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#7E44BC" bgcolor="7E44BC" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#943F07" bgcolor="943F07" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#5BD2C0" bgcolor="5BD2C0" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#F6E120" bgcolor="F6E120" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#808080" bgcolor="808080" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#7E9156" bgcolor="7E9156" draggable="true"
                                            ondragstart="drag(event)"></td>
                                    </tr>
                                    <tr>
                                        <td id="#83AFDB" bgcolor="83AFDB" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#F863CB" bgcolor="F863CB" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#B44848" bgcolor="B44848" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#F5D4B4" bgcolor="F5D4B4" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#FCA8CC" bgcolor="FCA8CC" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#CC8454" bgcolor="CC8454" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#BF6A1F" bgcolor="BF6A1F" draggable="true"
                                            ondragstart="drag(event)"></td>
                                        <td id="#FD9800" bgcolor="FD9800" draggable="true"
                                            ondragstart="drag(event)"></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <h3>Copy mode (beta)</h3>

                                <div class="well well-lg"><i>
                                    With copy mode active, you can click several stitches to select them at once. Click <b>Copy</b> to copy the
                                    selected stitches. Click <b>Paste</b> to paste the copied stitches to the selected
                                    area.
                                </i></div>
                                <button type="button" class="btn btn-primary btn-lg btn-block"
                                        onclick="select_or_change()" id="copymode" >Activate Copy Mode</button>
                                </br>
                                <div class="row">
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-primary btn-lg btn-block" onclick="copy()">Copy
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-primary btn-lg btn-block" onclick="paste(copylist)">Paste
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- GRID -->
                    <div class="col-md-6">
                        <h3>Click a stitch on the grid to change the stitch</h3>
                        <table id="grid" class="flexy">

                        </table>
                        <script>
                        var copylist = []
                        </script>

                    </div>
                </div>
            </div>



            <!-- SAVE AND SUBMIT TAB -->
            <div role="tabpanel" class="tab-pane" id="save_and_submit">
                <form action="{% url 'add_pattern' %}" name="pattern-form" id="pattern-form" method="post" class="ajax">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="title"><h3>Give your design a name:</h3></label>
                                <input type="text" name="title" class="form-control" id="title"
                                       placeholder="Enter name...">
                            </div>
                            <h3>Select a difficulty for your design:</h3>

                            <div class="radio">
                                <input type="radio" name="difficulty" id="radiohard" value="Hard">
                                <label for="radiohard">Hard</label>
                            </div>
                            <div class="radio">
                                <input type="radio" name="difficulty" id="radiomedium" value="Medium">
                                <label for="radiomedium">Medium</label>
                            </div>
                            <div class="radio">
                                <input type="radio" name="difficulty" id="radioeasy" value="Easy" checked>
                                <label for="radioeasy">Easy</label>
                            </div>


                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="description"><h3>Write a short description about your design:</h3></label>
                                <textarea name="description" rows="10" class="form-control" id="description"
                                          placeholder="Enter description..."></textarea>
                            </div>

                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6">

                                <input type="hidden" id="design_text" name="design" class="form-control"
                                       placeholder="Pattern text will show up here...">

                                <button id="submit" type="submit" class="btn btn-primary btn-lg btn-block">Submit
                                </button>
                            </div>
                        </div>
                        </div>
                        </form>
                    </div>

            </div>
            </form>

        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>


{% endblock %}

yarntail_project/templates/yarntail/edit_profile.html
{% extends 'yarntail/base.html' %}

{% load staticfiles %}s

{% block body_block %}

<div class="page-header">
    <h1>Edit Profile</h1>
</div>

<form role="form" method="post" enctype="multipart/form-data" action=".">
     {% csrf_token %}

        <div class="form-group" >
            <p class="required"> <label for="id_first_name"> First Name: </label>
                <input class="form-control"  id="id_first_name" maxlength="30" name="first_name" type="text"  placeholder="Enter first name"/></p>
        </div>
        <div class="form-group" >
            <p class="required"> <label for="id_last_name"> Last Name: </label>
                <input class="form-control"  id="id_last_name" maxlength="30" name="last_name" type="text"  placeholder="Enter last name"/></p>
        </div>
        <div class="form-group" >
            <p class="required"> <label for="id_date_of_birth"> Date Of Birth </label>
                <input class="form-control"  id="id_date_of_birth" name="date_of_birth" type="date"  placeholder="dob"/></p>
        </div>
        <div class="form-group">
            <p>
                    <input id="id_picture" type="file" class="" name="picture">
                </p>
        </div>
    <input type="submit" name="submit" value="Submit" />
</form>

{%endblock%}